export type AccountTransaction = {
  id: number;
  account_id: number;
  stock_code: string | null;
  transaction_date: string; // YYYY/MM/DD
  transaction_type: string;
  quantity: number | null;
  unit_price: number | null;
  fee: number | null;
  amount: number;
  tax: number | null;
  memo: string | null;
};

export const accounts = [
  { id: 1, name: "メイン口座" },
  { id: 2, name: "サブ口座" },
];

export const sampleTransactions: AccountTransaction[] = [
  {
    id: 1,
    account_id: 1,
    stock_code: null,
    transaction_date: "2025/01/01",
    transaction_type: "繰越",
    quantity: null,
    unit_price: null,
    fee: null,
    amount: 1000000,
    tax: null,
    memo: "前期繰越残高",
  },
  {
    id: 2,
    account_id: 2,
    stock_code: null,
    transaction_date: "2025/01/01",
    transaction_type: "繰越",
    quantity: null,
    unit_price: null,
    fee: null,
    amount: 824585,
    tax: null,
    memo: "前期繰越残高",
  },
  {
    id: 3,
    account_id: 2,
    stock_code: "2681",
    transaction_date: "2025/12/10",
    transaction_type: "配当金",
    quantity: 500,
    unit_price: null,
    fee: null,
    amount: 6774,
    tax: null,
    memo: "ゲオホールディングス",
  },
  {
    id: 4,
    account_id: 1,
    stock_code: "7012",
    transaction_date: "2025/12/18",
    transaction_type: "売却",
    quantity: 100,
    unit_price: 11930,
    fee: null,
    amount: 1186057,
    tax: null,
    memo: "川崎重工業",
  },
  {
    id: 5,
    account_id: 1,
    stock_code: "6580",
    transaction_date: "2025/12/18",
    transaction_type: "買付",
    quantity: 400,
    unit_price: 2978,
    fee: null,
    amount: -1198134,
    tax: null,
    memo: "ライトアップ",
  },
  {
    id: 6,
    account_id: 1,
    stock_code: null,
    transaction_date: "2025/12/18",
    transaction_type: "税金",
    quantity: null,
    unit_price: null,
    fee: null,
    amount: -24409,
    tax: null,
    memo: "譲渡益税源泉徴収金",
  },
  {
    id: 7,
    account_id: 1,
    stock_code: "2681",
    transaction_date: "2025/12/23",
    transaction_type: "売却",
    quantity: 500,
    unit_price: 1830,
    fee: null,
    amount: 909309,
    tax: null,
    memo: "ゲオホールディングス",
  },
  {
    id: 8,
    account_id: 1,
    stock_code: "9434",
    transaction_date: "2025/12/23",
    transaction_type: "買付",
    quantity: 5000,
    unit_price: 218.2,
    fee: null,
    amount: -1097494,
    tax: null,
    memo: "ソフトバンク",
  },
  {
    id: 9,
    account_id: 1,
    stock_code: null,
    transaction_date: "2025/12/23",
    transaction_type: "税金",
    quantity: null,
    unit_price: null,
    fee: null,
    amount: -20580,
    tax: null,
    memo: "譲渡益税源泉徴収金",
  },
  {
    id: 10,
    account_id: 1,
    stock_code: "5449",
    transaction_date: "2025/12/24",
    transaction_type: "買付",
    quantity: 400,
    unit_price: 2784,
    fee: null,
    amount: -1120193,
    tax: null,
    memo: "大阪製鐵",
  },
  {
    id: 11,
    account_id: 1,
    stock_code: "5449",
    transaction_date: "2025/12/29",
    transaction_type: "売却",
    quantity: 800,
    unit_price: 2805,
    fee: null,
    amount: 2232433,
    tax: null,
    memo: "大阪製鐵",
  },
  {
    id: 12,
    account_id: 1,
    stock_code: null,
    transaction_date: "2025/12/29",
    transaction_type: "税金",
    quantity: null,
    unit_price: null,
    fee: null,
    amount: -8213,
    tax: null,
    memo: "譲渡益税源泉徴収金",
  },
  {
    id: 13,
    account_id: 1,
    stock_code: null,
    transaction_date: "2025/12/30",
    transaction_type: "配当金",
    quantity: null,
    unit_price: null,
    fee: null,
    amount: 417,
    tax: null,
    memo: "ＭＲＦ分配金",
  },
  {
    id: 14,
    account_id: 1,
    stock_code: null,
    transaction_date: "2025/12/30",
    transaction_type: "再投資",
    quantity: null,
    unit_price: null,
    fee: null,
    amount: -417,
    tax: null,
    memo: "ＭＲＦ再投資",
  },
];
